server:
  port: 8085
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: IES-ED-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root@1234
    url: jdbc:mysql://localhost:3306/ies
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    compatibility-verifier:
      enabled: false
