accessKey: AKIA47CRV4ADLTZUXH6U
bucketName: correspondencenotices
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
region: ap-south-1
secret: df2Sw3OLmcOUEl0bY9HMZhyhd1raJISO9JAG2tgr
server:
  port: 8086
spring:
  application:
    name: IES-CO-API
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root@1234
    url: jdbc:mysql://localhost:3306/ies
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    password: ukoa bwdn jwti lens
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: padhibailochan19@gmail.com
