server:
  port: 8082
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


 

spring:
  application:
    name: IES-SSA-API
  cloud:
    compatibility-verifier:
      enabled: false
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: root@1234
#    url: jdbc:mysql://localhost:3306/iesar
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  cloud:
#    compatibility-verifier:
#      enabled: false

ssa:
  api:
    url: http://localhost:8082/api/ssn/{ssn}
